### ISSUE TITLE
Build Profile page (React) 

### ISSUE THREAD

**Issue by liverpoolka** [HRL-at-NYUSH/Interactive-Portal#49]
- [ ] Profile Settings page - as in the prototype (use input validation for password) 
- [x] Create 5 placeholder session history items (can be copied from prototype i. e.  Data-Tabs-Notes) 
- [x] Session history page with some interactivity (pop-up window when clicking on session history item)-as in prototype
- [x] Saved charts page with some interactivity (pop-up window when clicking on saved charts item)-as in prototype

**Comment by myteax** [comment]
What is the issue?
